spring:
  datasource:
    url: jdbc:mysql://localhost:3308/mydb
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  #      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#logging.level:
#  org.hibernate.sql: debug
#  org.hibernate.orm.jdbc.bind: trace
#  org.springframework.cache: debug

toss-payments:
  widget-secret: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

management:
  endpoints:
    web:
      exposure:
        include: caches